package e.commerce.with.java.ant;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jimit
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("    Welcome to Shoppable !!!");

        jButton15.setBackground(new java.awt.Color(204, 0, 0));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Exit");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Continue");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Terms of use for end user");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Do you agree with terms of use ?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Yes");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("No");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("Show Terms of use");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15))
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jButton1)
                .addGap(0, 405, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(114, 114, 114)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        int result;
        result=JOptionPane.showConfirmDialog(null, "Do you really want to exit the app ?",null, JOptionPane.YES_NO_OPTION);
        if (result==JOptionPane.YES_OPTION)
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JOptionPane.showMessageDialog(null, "You Need to fill all the details throughout the application to get most out of it.");
            new Sign_in().setVisible(true);

            WelcomePage w = new WelcomePage();

            w.setVisible(false);
            dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
jButton1.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
jTextArea1.append("Welcome to Shoppable.com. Shoppable.com Services LLC and/or its affiliates (\"Shoppable\") provide website features and other products and services to you when you visit or shop at Shoppable.com, use Shoppable products or services, use Shoppable applications for mobile, or use software provided by Shoppable in connection with any of the foregoing (collectively, \"Shoppable Services\"). By using the Shoppable Services, you agree, on behalf of yourself and all members of your household and others who use any Service under your account, to the following conditions.\n" +
"Please read these conditions carefully.\n" +
"\n" +
"We offer a wide range of Shoppable Services, and sometimes additional terms may apply. When you use an Shoppable Service (for example, Your Profile, Gift Cards, Shoppable Video, Your Media Library, Shoppable devices, or Shoppable applications) you also will be subject to the guidelines, terms and agreements applicable to that Shoppable Service (\"Service Terms\"). If these Conditions of Use are inconsistent with the Service Terms, those Service Terms will control.\n" +
"PRIVACY\n" +
"\n" +
"Please review our Privacy Notice, which also governs your use of Shoppable Services, to understand our practices.\n" +
"ELECTRONIC COMMUNICATIONS\n" +
"\n" +
" When you use Shoppable Services, or send e-mails, text messages, and other communications from your desktop or mobile device to us, you may be communicating with us electronically. You consent to receive communications from us electronically, such as e-mails, texts, mobile push notices, or notices and messages on this site or through the other Shoppable Services, such as our Message Center, and you can retain copies of these communications for your records. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.\n" +
"COPYRIGHT\n" +
"\n" +
"All content included in or made available through any Shoppable Service, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software is the property of Shoppable or its content suppliers and protected by United States and international copyright laws. The compilation of all content included in or made available through any Shoppable Service is the exclusive property of Shoppable and protected by U.S. and international copyright laws.\n" +
"TRADEMARKS\n" +
"\n" +
"Go to website to see a non-exhaustive list of Shoppable trademarks. In addition, graphics, logos, page headers, button icons, scripts, and service names included in or made available through any Shoppable Service are trademarks or trade dress of Shoppable in the U.S. and other countries. Shoppable's trademarks and trade dress may not be used in connection with any product or service that is not Shoppable's, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Shoppable. All other trademarks not owned by Shoppable that appear in any Shoppable Service are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Shoppable.\n" +
"LICENSE AND ACCESS\n" +
"\n" +
"Subject to your compliance with these Conditions of Use and any Service Terms, and your payment of any applicable fees, Shoppable or its content providers grant you a limited, non-exclusive, non-transferable, non-sublicensable license to access and make personal and non-commercial use of the Shoppable Services. This license does not include any resale or commercial use of any Shoppable Service, or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of any Shoppable Service or its contents; any downloading, copying, or other use of account information for the benefit of any third party; or any use of data mining, robots, or similar data gathering and extraction tools. All rights not expressly granted to you in these Conditions of Use or any Service Terms are reserved and retained by Shoppable or its licensors, suppliers, publishers, rightsholders, or other content providers. No Shoppable Service, nor any part of any Shoppable Service, may be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of Shoppable. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Shoppable without express written consent. You may not use any meta tags or any other \"hidden text\" utilizing Shoppable's name or trademarks without the express written consent of Shoppable. You may not misuse the Shoppable Services. You may use the Shoppable Services only as permitted by law. The licenses granted by Shoppable terminate if you do not comply with these Conditions of Use or any Service Terms.\n" +
"YOUR ACCOUNT\n" +
"\n" +
"You may need your own Shoppable account to use certain Shoppable Services, and you may be required to be logged in to the account and have a valid payment method associated with it. If there is a problem charging your selected payment method, we may charge any other valid payment method associated with your account. Visit Your Payments to manage your payment options. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your account, and you agree to accept responsibility for all activities that occur under your account or password. Shoppable does sell products for children, but it sells them to adults, who can purchase with a credit card or other permitted payment method. If you are under 18, you may use the Shoppable Services only with involvement of a parent or guardian. Parents and guardians may create profiles for teenagers in their Shoppable Household. Alcohol listings on Shoppable are intended for adults. You must be at least 21 years of age to purchase alcohol, or use any site functionality related to alcohol. Shoppable reserves the right to refuse service, terminate accounts, terminate your rights to use Shoppable Services, remove or edit content, or cancel orders in its sole discretion.\n" +
"REVIEWS, COMMENTS, COMMUNICATIONS, AND OTHER CONTENT\n" +
"You may post reviews, comments, photos, videos, and other content; send e-cards and other communications; and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights (including publicity rights), or otherwise injurious to third parties or objectionable, and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of \"spam\" or unsolicited commercial electronic messages. You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Shoppable reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.\n" +
"\n" +
"If you do post content or submit material, and unless we indicate otherwise, you grant Shoppable a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, perform, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant Shoppable and sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify Shoppable for all claims resulting from content you supply. Shoppable has the right but not the obligation to monitor and edit or remove any activity or content. Shoppable takes no responsibility and assumes no liability for any content posted by you or any third party.\n" +
"INTELLECTUAL PROPERTY COMPLAINTS\n" +
"\n" +
"Shoppable respects the intellectual property of others. If you believe that your intellectual property rights are being infringed, please follow our Notice and Procedure for Making Claims of Copyright Infringement.\n" +
"RISK OF LOSS\n" +
"\n" +
"All purchases of physical items from Shoppable are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.\n" +
"RETURNS, REFUNDS AND TITLE\n" +
"\n" +
"Shoppable does not take title to returned items until the item arrives at our fulfillment center. At our discretion, a refund may be issued without requiring a return. In this situation, Shoppable does not take title to the refunded item. For more information about our returns and refunds, please see our Returns Center.\n" +
"PRODUCT DESCRIPTIONS\n" +
"\n" +
"Shoppable attempts to be as accurate as possible. However, Shoppable does not warrant that product descriptions or other content of any Shoppable Service is accurate, complete, reliable, current, or error-free. If a product offered by Shoppable itself is not as described, your sole remedy is to return it in unused condition. \n" +
"PRICING\n" +
"\"List Price\" means the suggested retail price of a product as provided by a manufacturer, supplier, or seller. We regularly check List Prices against prices recently found on Shoppable and other retailers. Certain products may have a \"Was Price\" displayed, which is determined using recent price history of the product on Shoppable.\n" +
"\n" +
"With respect to items sold by Shoppable, we cannot confirm the price of an item until you order. Despite our best efforts, a small number of the items in our catalog may be mispriced. If the correct price of an item sold by Shoppable is higher than our stated price, we will, at our discretion, either contact you for instructions before shipping or cancel your order and notify you of such cancellation. Other merchants may follow different policies in the event of a mispriced item. \n" +
"\n" +
"We generally do not charge your credit card until after your order has entered the shipping process or, for digital products, until we make the digital product available to you.\n" +
"APP PERMISSIONS\n" +
"\n" +
"When you use apps created by Shoppable, such as the Shoppable App or Kindle App, you may grant certain permissions to us for your device. Most mobile devices provide you with information about these permissions. \n" +
"SANCTIONS AND EXPORT POLICY\n" +
"\n" +
"You may not use any Shoppable Service if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using Shoppable Services. You must comply with all U.S. or other export and re-export restrictions that may apply to goods, software (including Shoppable Software), technology, and services.\n" +
"OTHER BUSINESSES\n" +
"\n" +
"Parties other than Shoppable operate stores, provide services or software, or sell product lines through the Shoppable Services. In addition, we provide links to the sites of affiliated companies and certain other businesses. If you purchase any of the products or services offered by these businesses or individuals, you are purchasing directly from those third parties, not from Shoppable. We are not responsible for examining or evaluating, and we do not warrant, the offerings of any of these businesses or individuals (including the content of their Web sites). Shoppable does not assume any responsibility or liability for the actions, product, and content of all these and any other third parties. You should carefully review their privacy statements and other conditions of use. \n" +
"DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY\n" +
"\n" +
"THE SHOPPABLE SERVICES AND ALL INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) AND OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SHOPPABLE SERVICES ARE PROVIDED BY SHOPPABLE ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS, UNLESS OTHERWISE SPECIFIED IN WRITING. SHOPPABLE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE SHOPPABLE SERVICES, OR THE INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SHOPPABLE SERVICES, UNLESS OTHERWISE SPECIFIED IN WRITING. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SHOPPABLE SERVICES IS AT YOUR SOLE RISK.\n" +
"\n" +
"TO THE FULL EXTENT PERMISSIBLE BY LAW, SHOPPABLE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. SHOPPABLE DOES NOT WARRANT THAT THE SHOPPABLE SERVICES, INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SHOPPABLE SERVICES, SHOPPABLE'S SERVERS OR ELECTRONIC COMMUNICATIONS SENT FROM SHOPPABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. TO THE FULL EXTENT PERMISSIBLE BY LAW, SHOPPABLE WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF ANY SHOPPABLE SERVICE, OR FROM ANY INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH ANY SHOPPABLE SERVICE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE SPECIFIED IN WRITING.\n" +
"DISPUTES\n" +
"\n" +
"Any dispute or claim relating in any way to your use of any Shoppable Service will be adjudicated in the state or Federal courts in King County, Washington, and you consent to exclusive jurisdiction and venue in these courts. We each waive any right to a jury trial.\n" +
"APPLICABLE LAW\n" +
"\n" +
"By using any Shoppable Service, you agree that applicable federal law, and the laws of the state of Washington, without regard to principles of conflict of laws, will govern these Conditions of Use and any dispute of any sort that might arise between you and Shoppable.\n" +
"SITE POLICIES, MODIFICATION, AND SEVERABILITY\n" +
"\n" +
"Please review our other policies, such as our pricing policy, posted on this site. These policies also govern your use of Shoppable Services. We reserve the right to make changes to our site, policies, Service Terms, and these Conditions of Use at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.\n" +
"OUR ADDRESS\n" +
"\n" +
"Shoppable.com, Inc.\n" +
"P.O. Box 81226\n" +
"Seattle, WA 98108-1226\n" +
"\n" +
"ADDITIONAL SHOPPABLE SOFTWARE TERMS\n" +
"\n" +
"The following terms (“Software Terms”) apply to any software (including any updates or upgrades to the software) and any related documentation we make available to you in connection with Shoppable Services (the \"Shoppable Software\").\n" +
"\n" +
"     Use of the Shoppable Software. You may use Shoppable Software solely for purposes of enabling you to use the Shoppable Services as provided by Shoppable, and as permitted by these Conditions of Use and any Service Terms. You may not incorporate any portion of the Shoppable Software into other programs or compile any portion of it in combination with other programs, or otherwise copy (except to exercise rights granted in this section), modify, create derivative works of, distribute, assign any rights to, or license the Shoppable Software in whole or in part. All software used in any Shoppable Service is the property of Shoppable or its software suppliers and is protected by United States and international copyright laws.\n" +
"    Use of Third Party Services. When you use the Shoppable Software, you may also be using the services of one or more third parties, such as a wireless carrier or a mobile software provider. Your use of these third party services may be subject to the separate policies, terms of use, and fees of these third parties.\n" +
"     No Reverse Engineering. You may not reverse engineer, decompile or disassemble, tamper with, or bypass any security associated with the Shoppable Software, whether in whole or in part.\n" +
"    Updates. We may offer automatic or manual updates to the Shoppable Software at any time and without notice to you.\n" +
"     Government End Users. If you are a U.S. Government end user, we are licensing the Shoppable Software to you as a \"Commercial Item\" as that term is defined in the U.S. Code of Federal Regulations (see 48 C.F.R. § 2.101), and the rights we grant you to the Shoppable Software are the same as the rights we grant to all others under these Conditions of Use.\n" +
"    Conflicts. In the event of any conflict between these Conditions of Use and any other Shoppable or third-party terms applicable to any portion of Shoppable Software, such as open-source license terms, such other terms will control as to that portion of the Shoppable Software and to the extent of the conflict. \n" +
"");
 jRadioButton1.setEnabled(true);
 jRadioButton2.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
jButton1.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
